# Generated by Django 5.1.1 on 2024-09-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mobiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('colour', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'mobile_table',
            },
        ),
    ]
